import test from 'node:test';
import assert from 'node:assert/strict';
import { Room, createMap, intersects } from '../game.js';
import { CONFIG as C } from '../config.js';
function setup(){const r=new Room('TEST01','test');const k=r.addPlayer('killer'),a=r.addPlayer('alice'),b=r.addPlayer('bob');r.start(k.id);return {r,k,a,b};}
function press(r,p){p.input.space=false;r.tick(.01);p.input.space=true;r.tick(.01);}
test('one killer and at least two survivors are mandatory, host starts',()=>{const r=new Room('TEST01','test'),k=r.addPlayer('k'),a=r.addPlayer('a');assert.throws(()=>r.start(k.id),/최소 2명/);r.addPlayer('b');assert.throws(()=>r.start(a.id),/방장/);r.setRole(a.id,'killer');assert.equal([...r.players.values()].filter(p=>p.role==='killer').length,1);r.start(k.id);assert.equal(r.phase,'playing');assert.throws(()=>r.addPlayer('late'),/이미 시작/);});
test('movement ratio is 1.5 and diagonal speed is normalized; walls block',()=>{const {r,k,a}=setup();k.x=100;k.y=100;a.x=100;a.y=200;k.input={x:1,y:0,space:false};a.input={x:1,y:0,space:false};r.tick(.1);assert.equal(k.x-100,(a.x-100)*1.5);a.x=100;a.y=200;a.input={x:1,y:1,space:false};r.move(a,.1);assert.ok(Math.abs(Math.hypot(a.x-100,a.y-200)-17)<.0001);const w=r.map.walls[0];a.x=w.x-16;a.y=w.y+12;a.input={x:1,y:0,space:false};r.move(a,.1);assert.equal(a.x,w.x-16);assert.ok(!intersects(a.x,a.y,C.playerRadius,w));});
test('map exits always lie on opposing edges',()=>{for(let seed=1;seed<100;seed++){const m=createMap(seed),[a,b]=m.exits;assert.ok((a.x+b.x===m.width&&a.y===b.y)||(a.y+b.y===m.height&&a.x===b.x));assert.equal(m.generators.length,5);}});
test('generator progress persists, multiple workers do not shorten 60 seconds',()=>{const {r,a,b}=setup();const g=r.map.generators[0];a.x=g.x;a.y=g.y;a.input.space=true;for(let i=0;i<100;i++)r.tick(.1);assert.ok(Math.abs(g.progress-10)<.001);a.input.space=false;r.tick(1);assert.ok(Math.abs(g.progress-10)<.001);b.x=g.x+35;b.y=g.y;b.input.space=true;a.input.space=true;for(let i=0;i<500;i++)r.tick(.1);assert.ok(Math.abs(g.progress-60)<.001);assert.equal(g.progress,60);});
test('collision, carry, first cage, uninterrupted rescue and second cage elimination',()=>{const {r,k,a,b}=setup();k.x=a.x=100;k.y=a.y=100;r.tick(.01);assert.equal(a.status,'down');press(r,k);assert.equal(a.status,'carried');assert.equal(k.carrying,a.id);const cage=r.map.cages[0];k.x=cage.x;k.y=cage.y;press(r,k);assert.equal(a.status,'caged');assert.equal(a.cageCount,1);assert.equal(cage.occupant,a.id);k.x=1500;k.y=1200;b.x=cage.x+45;b.y=cage.y;b.input.space=true;for(let i=0;i<20;i++)r.tick(.1);assert.ok(cage.rescueProgress>1.9);b.input.space=false;r.tick(.1);assert.equal(cage.rescueProgress,0);b.input.space=true;for(let i=0;i<51;i++)r.tick(.1);assert.equal(a.status,'alive');assert.ok(a.immunity>0);assert.equal(cage.occupant,null);b.x=1000;b.y=1300;b.input.space=false;a.immunity=0;k.x=a.x;k.y=a.y;press(r,k);assert.equal(a.status,'carried');k.x=cage.x;k.y=cage.y;press(r,k);assert.equal(a.status,'out');assert.equal(a.cageCount,2);assert.equal(cage.occupant,null);a.input.space=true;r.tick(.01);assert.ok(a.spectateId);});
test('pallet is single use, stuns for two seconds and can be destroyed',()=>{const {r,k,a}=setup(),p=r.map.pallets[0];a.x=p.x+p.w/2;a.y=p.y+45;k.x=p.x+p.w/2+55;k.y=p.y+20;a.input.space=true;r.tick(.01);assert.equal(p.state,'dropped');assert.equal(k.stun,2);const x=k.x;k.input={x:1,y:0,space:false};r.tick(1);assert.equal(k.x,x);assert.equal(k.stun,1);a.input.space=false;k.input={x:0,y:0,space:true};r.tick(1);assert.equal(k.stun,0);r.tick(.5);assert.equal(p.state,'broken');a.input.space=true;r.tick(.1);assert.equal(p.state,'broken');});
test('cabinet conceals survivor until exit or killer inspection',()=>{const {r,k,a,b}=setup(),h=r.map.cabinets[0];b.x=100;b.y=100;a.x=h.x;a.y=h.y;press(r,a);assert.equal(a.hidden,h.id);const x=a.x;a.input.x=1;r.tick(.1);assert.equal(a.x,x);k.x=h.x+40;k.y=h.y;press(r,k);assert.equal(a.hidden,null);assert.equal(a.status,'down');assert.equal(h.occupant,null);});
test('all five generators open exits; escape and elimination end the game',()=>{const {r,a,b,k}=setup();a.x=r.map.exits[0].x;a.y=r.map.exits[0].y;r.tick(.01);assert.equal(a.status,'alive');for(const g of r.map.generators)g.progress=C.generatorSeconds;r.tick(.01);assert.equal(a.status,'escaped');b.status='out';r.tick(.01);assert.equal(r.phase,'finished');assert.equal(r.result.winner,'survivors');assert.equal(r.result.escaped,1);r.reset(k.id);assert.equal(r.phase,'lobby');r.start(k.id);assert.equal(r.map.generators[0].progress,0);assert.equal(a.status,'alive');});
test('disconnect grace ends match if killer does not return',()=>{const {r,k}=setup();k.connected=false;r.tick(29);assert.equal(r.phase,'playing');r.tick(1);assert.equal(r.result.winner,'survivors');});
test('carried survivor disconnect releases carrier without allowing a second imprisonment',()=>{const {r,k,a}=setup();k.carrying=a.id;a.status='carried';a.connected=false;r.tick(30);assert.equal(a.status,'out');assert.equal(k.carrying,null);assert.equal(a.cageCount,0);});
